# Generated by Django 5.1.6 on 2025-02-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('isbn', models.CharField(max_length=500)),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='library',
        ),
    ]
